### ISSUE TITLE
Modify link for deploy-with-olm.yaml to use downstream images

### ISSUE THREAD

**Issue by netzzer** [red-hat-storage/ocs-training#102]
**Do you need more detailed steps on an existing section? Please describe.**
Change link to http://pkgs.devel.redhat.com/cgit/containers/ocs-registry/plain/deploy-with-olm.yaml?h=ocs-4.2-rhel-8

**Comment by mulbc** [comment]
9a7c399e61e3986d0ea0d717459f74688ff9fc9c reverted this... downstream is only accessible inside the VPN and people reported issues with this approach...

We need to fix this differently... maybe give people a choice between downstream and upstream

**Comment by mulbc** [comment]
Current solutions to this that I can think of:

1. Provide the upstream and downstream links and let the student chose
1. Only provide the downstream link with a CAUTION note stating that it's VPN-only
  ** This means that non-RHT people won't be able to follow this
  ** This means that we have to have everyone at Hackfest dial into the VPN
1. Re-host the downstream deploy_with_olm.yaml somewhere public

Please discuss which of these options you prefer or what other option you can imagine

**Comment by netzzer** [comment]
If the downstream deploy-with-olm.yaml does not change frequently it can be copied while on the VPN and the resulting file could be uploaded to https://github.com/red-hat-storage/ocs-training/tree/master/ocp4ocs4. Then ocs4.adoc would just instruct the lab user to download from this location if the downstream image files are publicly available. 

This has to be solved for the HTB so I would think by the time of the Hackfest in Berlin there would be a way to do this without having to be on the Red Hat VPN.

**Comment by mulbc** [comment]
Closing this now, since we are now using a slightly different way to deploy and a very slim deploy_with_olm.yml
