### ISSUE TITLE
Remove local-storage operator content from ocs4.adoc

### ISSUE THREAD

**Issue by netzzer** [red-hat-storage/ocs-training#117]
**Describe the bug**
The local-storage operator pod and csv are no longer started in openshift-storage namespace. Need to remove references to local-storage operator/csv in ocs4.adoc. 
**Section in which you face the issue**
Provide the Section title or a link to the section
https://github.com/red-hat-storage/ocs-training/blob/master/ocp4ocs4/ocs4.adoc#installing-the-ocs-operator
**To Reproduce**
1. oc apply -f https://raw.githubusercontent.com/openshift/ocs-operator/release-4.2/deploy/deploy-with-olm.yaml

**Expected behavior**
local-storage operator/csv content removed

**Images**
$ oc get csv -n openshift-storage -o yaml | grep image:
                  image: rook/ceph:v1.1.4-27.gf20c056
                  image: noobaa/noobaa-operator:2.0.8
                  image: quay.io/ocs-dev/ocs-operator:4.2.0

**Comment by mulbc** [comment]
Good catch! I'll boot up a RHPDS lab and verify where we need to remove this...
