### ISSUE TITLE
Add steps to taint nodes

### ISSUE THREAD

**Issue by mulbc** [red-hat-storage/ocs-training#119]
Sometimes we actually want to prevent other apps to run inside of the OCS nodes. With the recent updates, we don't get the taint any more... we should document how to get the taint back ;)

**Comment by jeanchlopez** [comment]
Hi Chris,

can do that today as you are reaching the end of your day.

Where do you think we should add that piece? At the beginning or in the cluster expansion section?

JC

**Comment by netzzer** [comment]
This is in the OCS 4.2 Deployment documentation.

To add a taint to a node, use the following command:

$ oc adm taint nodes <node names> node.ocs.openshift.io/storage=true:NoSchedule
To find the tainted nodes, use the following command:

$ oc get nodes -o go-template='{{range $item := .items}}{{with $nodename := $item.metadata.name}}{{range $taint := $item.spec.taints}}{{if and (eq $taint.key "node.ocs.openshift.io/storage") (eq $taint.effect "NoSchedule")}}{{printf "%s\n" $nodename}}{{end}}{{end}}{{end}}{{end}}'
To remove the taint from a node, use the following command:

$ oc adm taint nodes <node name> node.ocs.openshift.io/storage-

**Comment by netzzer** [comment]
The instructions out of deployment guide are wrong. Should be this:

$ oc adm taint node <node_name> node.ocs.openshift.io/storage=true:NoSchedule
To find the tainted nodes, use the following command:

$ oc get nodes -o go-template='{{range $item := .items}}{{with $nodename := $item.metadata.name}}{{range $taint := $item.spec.taints}}{{if and (eq $taint.key "node.ocs.openshift.io/storage") (eq $taint.effect "NoSchedule")}}{{printf "%s\n" $nodename}}{{end}}{{end}}{{end}}{{end}}'
To remove the taint from a node, use the following command:

$ oc adm taint node <node_name> node.ocs.openshift.io/storage-

**Comment by netzzer** [comment]
Need to test this query after adding taint to ocs nodes:
```
oc get nodes -o go-template='{{range $item := .items}}{{with $nodename := $item.metadata.name}}{{range $taint := $item.spec.taints}}{{if and (eq $taint.key "node.ocs.openshift.io/storage") (eq $taint.effect "NoSchedule")}}{{printf "%s\n" $nodename}}{{end}}{{end}}{{end}}{{end}}'
```

**Comment by likid0** [comment]
We have a description on how to taint nodes in the following section: https://red-hat-storage.github.io/ocs-training/training/infra-nodes/ocs4-infra-nodes.html , closing issue.
