### ISSUE TITLE
Modify ocs4.adoc to be correct for deployment of OCS 4.2 GA

### ISSUE THREAD

**Issue by netzzer** [red-hat-storage/ocs-training#123]
**Do you need more detailed steps on an existing section? Please describe.**
Once OCS 4.2 is GA this section needs to be modified to be accurate for deployment steps:  
https://github.com/red-hat-storage/ocs-training/blob/master/ocp4ocs4/ocs4.adoc#installing-the-ocs-operator

**Comment by mulbc** [comment]
Already done
