### ISSUE TITLE
Need to add lib-bucket-provisioner CSV

### ISSUE THREAD

**Issue by netzzer** [red-hat-storage/ocs-training#125]
**Do you need more detailed steps on an existing section? Please describe.**
In this section - https://github.com/red-hat-storage/ocs-training/blob/master/ocp4ocs4/ocs4.adoc#installing-the-ocs-operator - need to add AWS S3 Operator in appropriate text and grahics. This awss3operator is deployed now for OCP 4.3 in the openshift-storage namespace and needs to be validated if it is also deployed for OCP 4.2.12 in openshift-storage.

New provisioner pod.
```
$ oc get pods | grep aws
aws-s3-provisioner-7bb4cccf47-4jvhn                               1/1     Running     0          24m
```
And CSV is now installed
```
$ oc get csv
NAME                    DISPLAY                       VERSION   REPLACES              PHASE
awss3operator.1.0.1     AWS S3 Operator               1.0.1     awss3operator.1.0.0   Succeeded
ocs-operator.v0.0.284   OpenShift Container Storage   0.0.284                         Succeeded
```

**Comment by jeanchlopez** [comment]
So just tested RC9 with OCP 4.2.12 and this new AWS S3 provisioner does not show up so it appears to be specific to OCP 4.3

```$ oc version
Client Version: openshift-clients-4.2.2-201910250432-8-g98a84c61
Server Version: 4.2.12
Kubernetes Version: v1.14.6+32dc4a0

$ oc get csv
NAME                    DISPLAY                       VERSION   REPLACES   PHASE
ocs-operator.v0.0.284   OpenShift Container Storage   0.0.284              Succeeded```

**Comment by netzzer** [comment]
Also need to test with OCP 4.3 on VMware to see if this operator is installed. Given it is used to create a AWS S3 bucket it most likely will not be deployed if on VMware.

**Comment by jeanchlopez** [comment]
Unless they reconfigure this to craete the bucket on the RGW. Will be interesting to see.

**Comment by netzzer** [comment]
The AWS S3 Operator is no longer used when deploying on OCP 4.3+. Instead it is this operator:
```
NAME                            DISPLAY                       VERSION        REPLACES   PHASE
lib-bucket-provisioner.v1.0.0   lib-bucket-provisioner        1.0.0                     Succeeded
ocs-operator.v4.3.0             OpenShift Container Storage   4.3.0                     Succeeded
```
