### ISSUE TITLE
OCP 4.3 Persistent Storage and Object Service Dashboards need to be updated

### ISSUE THREAD

**Issue by netzzer** [red-hat-storage/ocs-training#126]
**Do you need more detailed steps on an existing section? Please describe.**
The OCS Dashboards in OCP 4.3 have changed and need to be updated in this section - https://github.com/red-hat-storage/ocs-training/blob/master/ocp4ocs4/ocs4.adoc#installing-the-ocs-operator.

**Comment by netzzer** [comment]
Link with Dashboard comparisons for OCP 4.2 and OCP 4.3 - https://docs.google.com/document/d/1FdvbtG1TKg5FXWD-r82AabQ-ltEh3I_DTR_zBZp6duc/edit?usp=sharing.

**Comment by mulbc** [comment]
Please open a new branch for OCP 4.3 stuff and put your picture updates in there... that way it will be a lot easier to push the updates into master once we need OCP 4.3 content and also it will be much easier to compare the changes :)
