### ISSUE TITLE
Update section Matching PVs to RBDs to be consistent with RHPDS OCP+OCS labguide

### ISSUE THREAD

**Issue by netzzer** [red-hat-storage/ocs-training#129]
**Do you need more detailed steps on an existing section? Please describe.**
Need to update the section Matching PVs to RBDs with this new content for doing PV to RBD match RHPDS OCP+OCS roadshow workshop.

Get the full RBD name and the associated information for our postgreSQL PV
```
CSIVOL=$(oc get pv $(oc get pv | grep my-database-app | awk '{ print $1 }') -o jsonpath='{.spec.csi.volumeHandle}' | cut -d '-' -f 6- | awk '{print "csi-vol-"$1}')
echo $CSIVOL
```
```
TOOLS_POD=$(oc get pods -n openshift-storage -l app=rook-ceph-tools -o name)
oc rsh -n openshift-storage $TOOLS_POD rbd -p ocs-storagecluster-cephblockpool info $CSIVOL
```
Section to fix:
https://github.com/red-hat-storage/ocs-training/blob/master/ocp4ocs4/ocs4.adoc#matching-pvs-to-rbds

**Comment by mulbc** [comment]
I don't agree with changing it to these new commands, since it only shows how to map a single PV to an RBD... not how you can map multiple PVs (which can be important).
Therefore the relationship of the CSI metadata is not explained...

**Comment by jeanchlopez** [comment]
The previous set of instructions were doing the same and checking only one PV/PVC. At least this way we avoid the user copy/paste the wrong thing as it is automated. May be we can add some text before to explain what we grab in the command.
