### ISSUE TITLE
Error while subscribe to OCS 

### ISSUE THREAD

**Issue by SaravanaStorageNetwork** [red-hat-storage/ocs-training#135]
I was trying out OCS and facing the below error error:

This happens when I click on "Subscribe" to "Openshift container storage"

Uncaught (in promise) Error: Error "Invalid value: map[string]interface {}{"apiVersion":"operators.coreos.com/v1", "kind":"CatalogSourceConfig", "metadata":map[string]interface {}{"creationTimestamp":"2020-02-12T11:00:40Z", "generation":1, "name":"installed-redhat-openshift-storage", "namespace":"openshift-marketplace", "uid":"e84aef34-4d86-11ea-8df9-020d5627bd0e"}, "spec":map[string]interface {}{"csDisplayName":"Red Hat Operators", "csPublisher":"Red Hat", "packages":"ocs-operator", "targetNamespace":"openshift-storage"}}: validation failure list:

**Comment by SaravanaStorageNetwork** [comment]
This happens if I use the console present next to the terminal. 

But If i make use of the console (by using 
oc get -n openshift-console route console ) after logging in(with credentials provided), no issues.

**Comment by mulbc** [comment]
Hi! Thanks for opening this issue... it sounds like an OCS issue (and not necessarily an OCS Training issue with our docs)
Have you had this issue more than once? Which browser did you use?

**Comment by SaravanaStorageNetwork** [comment]
Yes, It is a bug while using the console tab present next to the terminal.
 It happens always. 
..looks like OCS issue only (maybe related to permission)

chrome browser.

**Comment by mulbc** [comment]
In that case, please open a Bugzilla ticket for OCS - let me know if you need help with that
