### ISSUE TITLE
Make the OCS training run on CRC

### ISSUE THREAD

**Issue by gbraad** [red-hat-storage/ocs-training#157]
Please have a look at https://github.com/code-ready/crc/issues/594 (https://github.com/code-ready/crc/issues/1190) and assist in tracing the issue why this does not work on CodeReady Containers.

**Comment by gbraad** [comment]
If they want to use the official Red Hat images, they need to be authenticated to the registry. The pull secret is not part of different namespace/project until someone add this explicitly. The default pull secret is only part of `openshift` namespace. The documentation does not specify this requirement.

**Comment by mulbc** [comment]
@ksingh7 is working on this for ODF-nano

**Comment by likid0** [comment]
The closest you will get is @ksingh7 work at: https://github.com/ksingh7/odf-nano. 

Closing this issue as the request is available in Karan's repo.
