### ISSUE TITLE
Fail adding new nodes

### ISSUE THREAD

**Issue by msakho** [red-hat-storage/ocs-training#158]
**Describe the bug**

While executing the instructions in the 2.1 section of the Lab in order to create the 3 additionnal worker nodes. The nodes are created with a state that is not shown:
There are the commands that I have ran:
CLUSTERID=$(oc get machineset -n openshift-machine-api -o jsonpath='{.items[0].metadata.labels.machine\.openshift\.io/cluster-api-cluster}')

curl -s https://raw.githubusercontent.com/red-hat-storage/ocs-training/master/ocp4ocs4/cluster-workerocs.yaml | sed -e "s/CLUSTERID/${CLUSTERID}/g" | oc apply -f -

oc get machines -n openshift-machine-api | egrep 'NAME|workerocs'

 oc get machines -n openshift-machine-api | egrep 'NAME|workerocs'
NAME                                                STATE     TYPE         REGION         ZONE            AGE
cluster-bsy-1601-r7xr5-workerocs-us-east-1a-4slq2                                                         24m
cluster-bsy-1601-r7xr5-workerocs-us-east-1b-smm85                                                         24m
cluster-bsy-1601-r7xr5-workerocs-us-east-1c-rzdgk                                                         24m

When I run the command to see if the new machines are added to the cluster, I'm not getting the expected results:
watch "oc get machinesets -n openshift-machine-api | egrep 'NAME|workerocs'"
NAME                                          DESIRED   CURRENT   READY   AVAILABLE   AGE
cluster-bsy-1601-r7xr5-workerocs-us-east-1a   1         1                             28m
cluster-bsy-1601-r7xr5-workerocs-us-east-1b   1         1                             28m
cluster-bsy-1601-r7xr5-workerocs-us-east-1c   1         1                             28m

Machines are never ready.

**Comment by mulbc** [comment]
Could you please add a screenshot of the last command's output or somehow ensure that the formatting is kept intact? It is hard to read & diagnose like this.

Usually when the new workers are not being provisioned, you have reached your account limit for the instance types. There should be warnings in your event stream and in monitoring about this.

**Comment by tkagn** [comment]
Verify the AMI ID - The Amazon Machine Instance Identifier. The identifier in the yaml file is 

`providerSpec:
        value:
          ami:
            id: ami-0eef624367320ec26`

Change the ami id to the ami id of a running machine of the same size. Try `ami-04a79d8d7cfa540cc` . Delete the machines and the machineset will recreate them along with the necessary nodes.

**Comment by srinivma1** [comment]
Not able to create machine sets in us-east2 region. Followed documentation mentioned in this repo and tried following command:

curl -s https://raw.githubusercontent.com/red-hat-storage/ocs-training/master/training/modules/ocs4/attachments/cluster-workerocs-us-east-2.yaml | sed -e "s/CLUSTERID/${CLUSTERID}/g" | oc apply -f -

But the extra machineset worker nodes are  not getting provisioned. It is stuck. and the machine sets are not getting to ready and available state.


NAME                                                       DESIRED   CURRENT   READY   AVAILABLE   AGE
cluster-60a9-d6xzd-workerocs-us-east-2a   1         1                                                    30m
cluster-60a9-d6xzd-workerocs-us-east-2b   1         1                                                    30m
cluster-60a9-d6xzd-workerocs-us-east-2c   1         1                                                     30m


Already tried with ami-04a79d8d7cfa540cc but still not working.
