### ISSUE TITLE
Install OCS version 4.2 restricted network environment

### ISSUE THREAD

**Issue by WaelGAmin** [red-hat-storage/ocs-training#169]
We are working on a restricted network environment, openshift Ver 4.3
and we need to install OCS ver 4.2 but as per the ocp 4.3 documentation the Operator Lifecycle Manager (OLM) always installs Operators from the latest version of an Operator catalog. 
https://docs.openshift.com/container-platform/4.3/operators/olm-restricted-networks.html#olm-understanding-operator-catalog-images_olm-restricted-networks
Please advise how can we install OCS version 4.2 on openshift 4.3 restricted network environment.

**Comment by mulbc** [comment]
Please make sure you select the right channel when you install OCS and also please set the update approval to `manual` - that should keep OCS at version 4.2.
We encourage people to use OCS version 4.3 for Openshift Container Platform 4.3 though.
