### ISSUE TITLE
Image and directions for 2.3. Getting to know the Storage Dashboards is incorrect for OCP 4.5.2

### ISSUE THREAD

**Issue by mid998** [red-hat-storage/ocs-training#171]
Section 2.3. Getting to know the Storage Dashboards references a "Dashboard" menu item that does not exist in OCP 4.5.2. 

https://github.com/red-hat-storage/ocs-training/blob/master/ocp4ocs4/ocs.adoc#23-getting-to-know-the-storage-dashboards

The first paragraph under 2.3 states "You can reach this by clicking on Home on your left navigation bar, then selecting Dashboards". However, there is no Dashboard menu item. The dashboards are present in the Overview menu and /dashboards/ is part of the Overview URL. 

Not sure if this is an OCP 4.5.2 bug and the Dashboard menu should be present or if the Dashboard menu is really gone and documentation here and in https://docs.openshift.com/container-platform/4.5/web_console/using-dashboard-to-get-cluster-information.html is incorrect. 

My cluster:
<img width="1037" alt="Screen Shot 2020-07-23 at 2 44 05 PM" src="https://user-images.githubusercontent.com/68707369/88333592-839bb280-ccfe-11ea-88a0-efbc7b44cef3.png">

**Comment by mulbc** [comment]
Thanks for reporting this! We will have to do some more changes for OCP 4.5 and will include this change then.

**Comment by mulbc** [comment]
Issue is fixed in current version
