### ISSUE TITLE
Shared storage example is a deploymentconfig not a deployment

### ISSUE THREAD

**Issue by saberkan** [red-hat-storage/ocs-training#186]
**Describe the bug**
When deploying the shared storage example, the following error occurs:
`$ oc set volume deployment/file-uploader --add --name=my-shared-storage -t pvc --claim-mode=ReadWriteMany --claim-size=1Gi --claim-name=my-shared-storage --claim-class=ocs-storagecluster-cephfs --mount-path=/opt/app-root/src/uploaded -n my-shared-storage
Error from server (NotFound): deployments.extensions "file-uploader" not found
`
**Section in which you face the issue**
Create of shared storage example

**To Reproduce**
1. Deploy OCS
2. Follow shared storage section

**Expected behavior**
Storage needs to be updated in the deployment config with this command (not with deployment):
```
oc set volume deploymentconfig/file-uploader --add --name=my-shared-storage -t pvc --claim-mode=ReadWriteMany --claim-size=1Gi --claim-name=my-shared-storage --claim-class=ocs-storagecluster-cephfs --mount-path=/opt/app-root/src/uploaded -n my-shared-storage
deploymentconfig.apps.openshift.io/file-uploader volume updated
```

**Screenshots**
NA
**Environment**
NA

**Did you use OCP deployed by the RHPDS workshop?**
Opentlc

**Additional context**
NA

**Comment by mulbc** [comment]
Fixed by https://github.com/red-hat-storage/ocs-training/commit/5caa66360e79af0eda7940a5d7b0a80ae0217d74
