### ISSUE TITLE
Set default storageclass

### ISSUE THREAD

**Issue by e-minguez** [red-hat-storage/ocs-training#188]
OCS doesn't configure a default storageclass, something like:

```
oc patch storageclass ocs-storagecluster-cephfs -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
```

Would be nice to include after a successful installation.

**Comment by mulbc** [comment]
This repo is only for providing guides on how to _use_ OCS/ODF. I think your suggestion would be better suited in the actual ocs operator repo: https://github.com/openshift/ocs-operator
