### ISSUE TITLE
[Core] Create section on how to troubleshoot Ceph using the rook-ceph toolbox 

### ISSUE THREAD

**Issue by netzzer** [red-hat-storage/ocs-training#19]
Upstream documentation - https://rook.io/docs/rook/v1.1/ceph-toolbox.html - for deployment an usage. Will need to modify namespace in yaml file if the toolbox is not provided with OCS4.2.

**Comment by mulbc** [comment]
@netzzer See the current toolbox chapter, which includes everything that was in the previous rook workshop - is that enough or do you expect anything in addition?

**Comment by mulbc** [comment]
Ready for review - closing
