### ISSUE TITLE
[Core] Create section on how to expand the storage for Ceph cluster using existing nodes

### ISSUE THREAD

**Issue by netzzer** [red-hat-storage/ocs-training#20]
This section would focus on how to expand storage using existing OCP/OCS nodes (nodes with ocs label) using the OCP web console. Instruction should include how to validate additional storage both in using OCP dashboards and ceph commands via toolbox.

**Comment by mulbc** [comment]
@netzzer Do you know how to do this? I don't.... If so, please provide the steps/commands

**Comment by mulbc** [comment]
![image](https://user-images.githubusercontent.com/131446/67221926-8e9e7b00-f42c-11e9-9ac5-732e3b821a05.png)

Using the options menu in the Storage Cluster list
