### ISSUE TITLE
[Core] Create section on how to upgrade Ceph from one version to another

### ISSUE THREAD

**Issue by netzzer** [red-hat-storage/ocs-training#22]
Being able to do this activity requires that there is a supported ceph version to upgrade to.

**Comment by mulbc** [comment]
I'll tag it as "enhancement" so we know that it's an optional thing that we might not be able to implement...

**Comment by netzzer** [comment]
Why is this closed?

**Comment by netzzer** [comment]
Not planning on adding this section given need to start with older version so upgrade can happen.
