### ISSUE TITLE
Manual OpenShift Regional Disaster Recovery - updates for 4.8

### ISSUE THREAD

**Issue by AviadP** [red-hat-storage/ocs-training#220]
**Describe the bug**
Some commands that worked with ocs 4.7, need to be updated in order to work with 4.8

**Section in which you face the issue**
1. in https://red-hat-storage.github.io/ocs-training/RegionalDR/manual/ocs4-multisite-replication.html#_bootstrap_peer_clusters:
this command: `oc --kubeconfig site2/auth/kubeconfig get cephblockpools.ceph.rook.io replicapool -n openshift-storage -o jsonpath='{.status.mirroringInfo.summary.summary.site_name}{"\n"}'` need to be changed into: `oc --kubeconfig site2/auth/kubeconfig get cephblockpools.ceph.rook.io replicapool -n openshift-storage -o jsonpath='{.status.mirroringInfo.site_name}{"\n"}'`
2. also, same section, this output: `b888de61-8520-4381-a883-366e64bd400f-openshift-storage` no longer has post-fix of `openshift-storage`
3. this 2 changes need to be made twice - for primary and secondary clusters 
4. in https://red-hat-storage.github.io/ocs-training/RegionalDR/manual/ocs4-multisite-replication.html#_create_rbd_mirror_custom_resource, command: `SECRET=$(oc get secrets | grep openshift-storage | awk {'print $1}')` will not work with `grep openshift-storage` due to change described above (2)
5. same section, command `oc get cephblockpools.ceph.rook.io replicapool -n openshift-storage -o jsonpath='{.status.mirroringStatus.summary.summary}{"\n"}'` need to be changed to `oc get cephblockpools.ceph.rook.io replicapool -n openshift-storage -o jsonpath='{.status.mirroringStatus}{"\n"}'`

**Comment by mulbc** [comment]
I agree and thanks for checking on this, but we're not yet ready for OCS 4.8 and will keep this issue open until we update the docs for that.
Thanks for your contribution!

**Comment by likid0** [comment]
Closing Issue, as the suggestions have been fixed and obsoleted in the 4.10 documentation for RDR
