### ISSUE TITLE
Move YAML files into attachement folder

### ISSUE THREAD

**Issue by mulbc** [red-hat-storage/ocs-training#222]
RE: https://github.com/red-hat-storage/ocs-training/pull/221

By moving the content to files in attachement, it will become easier for people to apply the file content.
Also this is 4.3 of the contribution guide

**Comment by likid0** [comment]
As discussed we will use the 'files in the attachment folder approach' with all new content generated and also when doing maintenance of old content per the contribution guide instructions. Closing this issue
