### ISSUE TITLE
Do not use Vault in dev mode

### ISSUE THREAD

**Issue by mulbc** [red-hat-storage/ocs-training#223]
RE https://github.com/red-hat-storage/ocs-training/pull/221

The way Vault is set up, the data is only retained in memory. Whenever it is restarted, all data will be lost.
Make sure Vault is not in dev, but in prod mode and clean up the init script.

**Comment by mulbc** [comment]
At best link people to the official Helm Chart for Vault on OpenShift for the install:
https://www.vaultproject.io/docs/platform/k8s/helm/openshift

**Comment by likid0** [comment]
This issue has been addressed with the new PR you provided for the vault deployment @mulbc , so closing this issue.
