### ISSUE TITLE
Feedback for ocs4-metro-stretched.adoc

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-training#227]
List of minor issues in `ocs4-metro-stretched.adoc`:

- [ ] *Figure 1. OpenShift nodes and ODF daemons* doesn't show all nodes, it
  shows storage nodes only, which is confusing when we talk about whole OCP
  cluster here
- [ ] 4.1. ODF Operator Deployment: it's no longer necessary to create
  namespace and label it manually
- [ ] screenshot *Figure 13. LSO Discovery Parameters* shows a node without
  a zone label - that is an invalid configuration
- [ ] there is only one ceph-mgr pod in *4.2.1. Validate Cluster Deployment*, while we expect that there are 2
- [ ] there is no rgw pod in *4.2.1. Validate Cluster Deployment*, so one
  could be confused (since we support this on premise, where we expect one in each data zone)
- [ ] Use value smaller than actual disk size: OCP Console just sets there "1" and doesn't bother with actual number

**Comment by netzzer** [comment]
This content has now been moved to 2 new OCS 4.8 docs (see below). Please reference new content in official docs.

https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.8/html/configuring_openshift_container_storage_for_metro-dr_stretch_cluster/index
AND
https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.8/html/recovering_a_metro-dr_stretch_cluster/index

**Comment by likid0** [comment]
Closing the issue as the recommendations/comments have been addressed in the official docs
