### ISSUE TITLE
[Core] Create section on how to upgrade OCS 4.2

### ISSUE THREAD

**Issue by netzzer** [red-hat-storage/ocs-training#23]
Need to investigate what this means and is it possible given need target to upgrade to.

**Comment by mulbc** [comment]
I'll tag it as "enhancement" so we know that it's an optional thing that we might not be able to implement...
This should go through the regular operator upgrade mechanism... so maybe we can talk about the theory a bit?

**Comment by netzzer** [comment]
Why is this closed?

**Comment by netzzer** [comment]
Not planning on adding this section given need to start with older version so upgrade can happen.
