### ISSUE TITLE
[Workload] Create section for Openshift Registry on OCS 4.2

### ISSUE THREAD

**Issue by netzzer** [red-hat-storage/ocs-training#27]
Create asciidoc training content for how to deploy Openshift Registry using OCS 4.2.

**Comment by mulbc** [comment]
As part of the CephFS example deployment, the basic things around the OCP Registry were already discussed.
https://github.com/red-hat-storage/ocs-training/blob/master/ocp4ocs4/ocs4.adoc#3-create-a-new-ocp-deployment-using-cephfs

This covered a newly deployed registry - what I would still expect to see is how the already present registry that lives inside of OCP can be moved (while retaining the data) onto OCS.
