### ISSUE TITLE
Review oc client setup using a Mac

### ISSUE THREAD

**Issue by mulbc** [red-hat-storage/ocs-training#35]
Review steps in the oc client set up on a mac please :)

**Comment by mulbc** [comment]
Section link:
https://github.com/red-hat-storage/ocs-training/blob/master/ocp4ocs4/ocs4.adoc#13-configuring-the-local-oc-client

**Comment by mulbc** [comment]
https://github.com/red-hat-storage/ocs-training/blob/master/ocp4ocs4/ocs4.adoc#configuring-the-local-oc-client

**Comment by netzzer** [comment]
This section needs to be fixed. Need to change 'linux-' to 'mac-' and `sudo mv oc /usr/bin` fails on macbook, even when entering sudo password. 

This section will explain how you set up your workstation with the Openshift CLI.

To get the latest Openshift CLI client run the following commands:

Mac steps
```
wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/ --no-directories --accept="*client-mac*" --quiet --recursive --level=1
ls -1 openshift-client-linux-*.tar.gz | tail -n1 | xargs -I {} tar xzvf {} oc
sudo mv oc /usr/bin
```
