### ISSUE TITLE
Add example for using the OBC that was created with Noobaa

### ISSUE THREAD

**Issue by mulbc** [red-hat-storage/ocs-training#47]
**Do you need more detailed steps on an existing section? Please describe.**
New section for OBC example

**Describe what you would like to see**
We created a new OBC in the training, but don't use it. I want to see an example of pushing a new file using s3cmd.
As an example we could use a [Docker container](https://github.com/ateliedocodigo/docker-s3cmd) that has s3cmd pre-installed and forward the ConfigMap and secret that Noobaa already creates.

**Describe alternatives you've considered**
-None-

**Comment by tamireran** [comment]
**Introduction**
The OpenShift Container Storage platform introduces a new concept called Object Bucket Claim. 
Similar to Persistent Volumes, developers can add a few more lines to their deployment YAML and get the endpoint, access key and secret key available as environment variables.

The instructions below includes an example of a job. The first part is the Object Bucket Claim itself. 

> 
> apiVersion: objectbucket.io/v1alpha1
> kind: ObjectBucketClaim
> metadata:
>   name: "obc-test"
> spec:
>   generateBucketName: "obc-test-noobaa"
>   storageClassName: openshift-storage.noobaa.io
> 

The second part is the mapping between the bucket claim result - which is a config map with data and a secret with the credentials. 

> apiVersion: batch/v1
> kind: Job
> metadata:
>   name: obc-test
> spec:
>   template:
>     spec:
>       restartPolicy: OnFailure
>       containers:
>         - image: quay.io/etamir/training:latest
>           name: obc-test
>           env:
>             - name: BUCKET_NAME
>               valueFrom:
>                 configMapKeyRef:
>                   name: obc-test
>                   key: BUCKET_NAME
>             - name: BUCKET_HOST
>               valueFrom:
>                 configMapKeyRef:
>                   name: obc-test
>                   key: BUCKET_HOST
>             - name: BUCKET_PORT
>               valueFrom:
>                 configMapKeyRef:
>                   name: obc-test
>                   key: BUCKET_PORT
>             - name: AWS_ACCESS_KEY_ID
>               valueFrom:
>                 secretKeyRef:
>                   name: obc-test
>                   key: AWS_ACCESS_KEY_ID
>             - name: AWS_SECRET_ACCESS_KEY
>               valueFrom:
>                 secretKeyRef:
>                   name: obc-test
>                   key: AWS_SECRET_ACCESS_KEY
>             - name: AWS_DEFAULT_REGION
>               value: "us-east-1"
>           volumeMounts:
>             - name: training-persistent-storage
>               mountPath: /data
>       volumes:
>       - name: training-persistent-storage
>         emptyDir: {}

This specific job will simply claim Object Bucket from NooBaa, which will create a bucket and an account. 
The application in this job will do the following:
1. Read the result of the claim from a config map and secret, using environment variables
2. Download sample dataset
3. Upload the dataset to the newly created bucket
4. Download the dataset to a new folder and compare md5 
5. Report success (or failure)
 
`curl https://noobaa-public.s3.amazonaws.com/training/training.yaml -O`

To run this job use the following command:

`oc create -f training.yaml`

Once the job is in Complete status run the following command:

`oc logs obc-test-<use your own pod name`

Expect to see the following test in the last line: **_successful test_**

**Comment by netzzer** [comment]
Can you attach the yaml files to this Issue please?

**Comment by mulbc** [comment]
I think the yaml file is the second block that he pasted

**Comment by mulbc** [comment]
@tamireran I heard you want to push this into a separate Workload? Is this still the case or should I add this to the core module?!
If you want to contribute a workload module, I'll close this issue though to maintain overview of what we need to work on.

**Comment by tamireran** [comment]
> @tamireran I heard you want to push this into a separate Workload? Is this still the case or should I add this to the core module?!
> If you want to contribute a workload module, I'll close this issue though to maintain overview of what we need to work on.

@mulbc I didn't push into a separate workload. I think it should be part of the core module.
