### ISSUE TITLE
ocp4ocs4 lab needs a few updates around fixing noobaa-core-0

### ISSUE THREAD

**Issue by wkulhanek** [red-hat-storage/ocs-training#51]
Section 2.2.1 in the ocp4ocs4 document needs an explanation on how to deploy rook toolbox. Also I had to delete the noobaa-core-0 pod afer fixing things in the toolbox. Finally after doing that my noobaa-operator panics:

time="2019-10-25T18:14:18Z" level=info msg="✈️  RPC: auth.read_auth() Request: <nil>"
time="2019-10-25T18:14:18Z" level=info msg="✅ RPC: auth.read_auth() Response OK: &{Op:res RequestID:1@https://::ffff:10.131.0.1:46152(hzhprug) Took:0.1704470000040601 Error:<nil>}"
time="2019-10-25T18:14:18Z" level=info msg="SetPhase: \"Configuring\"" sys=openshift-storage/noobaa
time="2019-10-25T18:14:18Z" level=info msg="✅ Exists: Secret \"noobaa-operator\"\n"
time="2019-10-25T18:14:18Z" level=info msg="✅ Exists: Secret \"noobaa-admin\"\n"
time="2019-10-25T18:14:18Z" level=info msg="❌ Not Found: BackingStore \"noobaa-default-backing-store\"\n"
time="2019-10-25T18:14:18Z" level=info msg="✅ Exists:  \"noobaa-cloud-creds-secret\"\n"
time="2019-10-25T18:14:18Z" level=info msg="Secret noobaa-cloud-creds-secret was created succesfully by cloud-credentials operator" func=ReconcileDefaultBackingStore sys=openshift-storage/noobaa
time="2019-10-25T18:14:18Z" level=panic msg="☠️  Panic Attack: [] failed to parse AWS region from node name ip-10-0-133-98.ec2.internal"

**Comment by mulbc** [comment]
Right, we should probably link to the toolbox section :/

Unfortunately the noobaa-operator issue is known, only happens in us-east-1 deployment and is due to it deploying the (old) version 2.0.2.

I will have to check in with engineering why they switched back to 2.0.2 instead of 2.0.3 (which includes the fix)
