### ISSUE TITLE
Make executable commands Homeroom compatible

### ISSUE THREAD

**Issue by mulbc** [red-hat-storage/ocs-training#56]
Executable commands, like in https://github.com/red-hat-storage/ocs-training/blob/master/ocs4kafka/Readme.adoc#L24 should be tagged as executable with `[source,role="execute"]`

Example:

Transform this:
```
----
oc new-project amq-streams
----
```

Into this:
```
[source,role="execute"]
----
oc new-project amq-streams
----
```

Inside of Homeroom, this will add a little button that will allow people to directly execute these commands without typing them themselves

**Comment by ksingh7** [comment]
fixed in #59
