### ISSUE TITLE
Do not require people to pull the repository

### ISSUE THREAD

**Issue by mulbc** [red-hat-storage/ocs-training#57]
Expect people to not pull the ocs-training repository.

If you want to apply a specific file, use the raw link from within Github
![ocs-training 2019-10-28 14-24-16](https://user-images.githubusercontent.com/131446/67681958-a32fc580-f98e-11e9-8389-9ee965a8792e.png)

Therefore change 
````
- Create kafka topic
```
oc apply -f 02-kafka-topic.yaml
```
````

to:
````
- Create kafka topic
----
oc apply -f https://github.com/red-hat-storage/ocs-training/raw/master/ocs4kafka/02-kafka-topic.yaml
----
````

in all locations that apply

**Comment by ksingh7** [comment]
fixed in #59
