### ISSUE TITLE
Use ASCIIdoc keyboard attributed for shortcuts

### ISSUE THREAD

**Issue by mulbc** [red-hat-storage/ocs-training#58]
Instead of 

```
press ``ctrl+c`` to cancel
```

Please use
```
press kbd:[Ctrl+C] to cancel
```

For this to work, you need to first activate the `experimental` features in your document by adding this to the top:
```
// Activate experimental attribute for Keyboard Shortcut keys
:experimental:
```

We use this in our main document as well

**Comment by ksingh7** [comment]
fixed in #59
