### ISSUE TITLE
The SED commands in cluster scale up does not work on OSX terminal

### ISSUE THREAD

**Issue by ksingh7** [red-hat-storage/ocs-training#61]
**Describe the bug**

**Section in which you face the issue**
section 2.1

**To Reproduce**
- After setting CLUSTERID shell variable, run the command from OSX terminal
```
sed -i "s/cluster-28cf-t22gs/$CLUSTERID/g" cluster-workerocs-us-east-1a.yaml
```

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/9701902/67711981-17975280-f9e9-11e9-8fd0-c122085f8a5d.png)

**Environment**
 - OS: OSX

**Did you use OCP deployed by the RHPDS workshop?**
Yes

**Additional context**

**Comment by ksingh7** [comment]
@mulbc @netzzer you might want to add a note for OSX users to use an extra ``  " " ``  after `` sed -i `` , as shown below ( worked for me )

![image](https://user-images.githubusercontent.com/9701902/67712142-6c3acd80-f9e9-11e9-9b63-eb89bf7fbc78.png)

**Comment by mulbc** [comment]
From my memory: `-i " "` will add a backup file that looks the same, but has one whitespace appended to it... Made me mad one time...
Thanks for the bug report! I'll look into this tomorrow, but vaguely remember that there was an issue there...

Maybe it's time to use something more sophisticated like https://github.com/kolypto/j2cli

**Comment by netzzer** [comment]
Adding this in new PR for branch ocs42-fix4.

Mac steps
```
sed -i '' "s/cluster-28cf-t22gs/$CLUSTERID/g" cluster-workerocs-us-east-1a.yaml
sed -i '' "s/cluster-28cf-t22gs/$CLUSTERID/g" cluster-workerocs-us-east-1b.yaml
sed -i '' "s/cluster-28cf-t22gs/$CLUSTERID/g" cluster-workerocs-us-east-1c.yaml
```
Also have `Linux steps`

**Comment by tamireran** [comment]
Using MacOS Catalina, sed command should look like that (no space between the -i and the ""

> sed -i"" "s/cluster-28cf-t22gs/$CLUSTERID/g" cluster-workerocs-us-east-1a.yaml
> sed -i"" "s/cluster-28cf-t22gs/$CLUSTERID/g" cluster-workerocs-us-east-1b.yaml
> sed -i"" "s/cluster-28cf-t22gs/$CLUSTERID/g" cluster-workerocs-us-east-1c.yaml

**Comment by mulbc** [comment]
@netzzer can you please check and acknowledge?
