### ISSUE TITLE
podman pull docker.io/library/alpine fails on Mac OS 10.14.6

### ISSUE THREAD

**Issue by netzzer** [red-hat-storage/ocs-training#62]
**Describe the bug**
Installed podman using instructions in provided link (brew cask install podman) and then attemped the `sudo podman pull docker.io/library/alpine`.
**Section in which you face the issue**
https://github.com/red-hat-storage/ocs-training/tree/master/ocp4ocs4#create-a-new-ocp-deployment-using-cephfs

**To Reproduce**
1. Install podman on Mac OS 
2. sudo podman pull docker.io/library/alpine
3. See error
Error: could not get runtime: dial unix /run/podman/io.podman: connect: no such file or directory
**Expected behavior**
Pulls image correctly.

**Environment**
 - OS: Mac OS 10.14.6

**Did you use OCP deployed by the RHPDS workshop?**
Yes, using local Macbook for oc client commands.

**Comment by jeanchlopez** [comment]
Found this particular podman issue upstream:
https://github.com/containers/libpod/issues/3882

Looks like the MAC podman client requires a podman install on a linux box to operate.

**Comment by mulbc** [comment]
Will be solved by https://github.com/red-hat-storage/ocs-training/issues/70

**Comment by mulbc** [comment]
Solved by https://github.com/red-hat-storage/ocs-training/pull/75
