### ISSUE TITLE
noobaa status differs from guide

### ISSUE THREAD

**Issue by jeanchlopez** [red-hat-storage/ocs-training#65]
**Describe the bug**
When issuing the nooba status client from my RHEL 7.6 client I get the following display
INFO[0001] ✅ (Optional) Exists: ServiceMonitor "noobaa-service-monitor"
INFO[0001] ✅ Exists: PersistentVolumeClaim "db-noobaa-core-0"
INFO[0001] ❌ System Phase is "Configuring"
INFO[0001] ⏳ System Phase is "Configuring". Waiting for phase ready ...

**Section in which you face the issue**
Nooba client testing and OBC creation

**To Reproduce**
Haven't reproduced yet but environment is:
1. Install RHEL 7.6 noobaa client
2. oc login into OCP cluster
3. oc project openshift-storage
4. noobaa status

**Expected behavior**
The output should display the following entries
INFO[0003] ✅ (Optional) Exists: ServiceMonitor "noobaa-service-monitor"
INFO[0004] ✅ Exists: PersistentVolumeClaim "db-noobaa-core-0"
INFO[0004] ✅ System Phase is "Ready"
INFO[0004] ✅ Exists: Secret "noobaa-admin"

**Screenshots**
See higher
**Environment**
 - OS: RHEL 7.6
 - SSH CLI

**Did you use OCP deployed by the RHPDS workshop?**
No OpenTLC

**Additional context**
Add any other context about the problem here.This difference in output does not prevent me from completing the lab and to create and display all the information related to the OBC.

[root@ceph-admin ~]# noobaa obc create test21obc
INFO[0000] ✅ Created: ObjectBucketClaim "test21obc"
[root@ceph-admin ~]# noobaa status
...
truncated
...
#-----------------#
#- Bucket Claims -#
#-----------------#

NAMESPACE           NAME        BUCKET-NAME                                      STORAGE-CLASS                 BUCKET-CLASS   PHASE
openshift-storage   test21obc   test21obc-ec1f2379-c44c-4c7b-85eb-ce2249be4a1b   openshift-storage.noobaa.io                  Bound

[root@ceph-admin ~]# oc get obc
NAME        STORAGE-CLASS                 PHASE   AGE
test21obc   openshift-storage.noobaa.io   Bound   36s
[root@ceph-admin ~]# oc get obc test21obc -o yaml
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  creationTimestamp: "2019-10-29T00:49:36Z"
  finalizers:
  - objectbucket.io/finalizer
  generation: 2
  labels:
    app: noobaa
    bucket-provisioner: openshift-storage.noobaa.io-obc
    noobaa-domain: openshift-storage.noobaa.io
  name: test21obc
  namespace: openshift-storage
  resourceVersion: "176515"
  selfLink: /apis/objectbucket.io/v1alpha1/namespaces/openshift-storage/objectbucketclaims/test21obc
  uid: fb1d5c62-f9e5-11e9-9159-0a0e10271dfb
spec:
  ObjectBucketName: obc-openshift-storage-test21obc
  bucketName: test21obc-ec1f2379-c44c-4c7b-85eb-ce2249be4a1b
  generateBucketName: test21obc
  storageClassName: openshift-storage.noobaa.io
status:
  phase: Bound
[root@ceph-admin ~]# oc get -n openshift-storage secret test21obc -o yaml
apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: cEZXcmRLYmFmSXJvS2VpTGZOb0o=
  AWS_SECRET_ACCESS_KEY: d1l2dm1LYjJWdHZIYWFMdjhhbWpXZFFtQzNMazhWeHhkeHdieEdaag==
kind: Secret
metadata:
  creationTimestamp: "2019-10-29T00:49:36Z"
  finalizers:
  - objectbucket.io/finalizer
  labels:
    app: noobaa
    bucket-provisioner: openshift-storage.noobaa.io-obc
    noobaa-domain: openshift-storage.noobaa.io
  name: test21obc
  namespace: openshift-storage
  ownerReferences:
  - apiVersion: objectbucket.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ObjectBucketClaim
    name: test21obc
    uid: fb1d5c62-f9e5-11e9-9159-0a0e10271dfb
  resourceVersion: "176510"
  selfLink: /api/v1/namespaces/openshift-storage/secrets/test21obc
  uid: fb3649d1-f9e5-11e9-bbf3-0204af9750f1
type: Opaque
[root@ceph-admin ~]# oc get -n openshift-storage cm test21obc -o yaml
apiVersion: v1
data:
  BUCKET_HOST: 10.0.155.207
  BUCKET_NAME: test21obc-ec1f2379-c44c-4c7b-85eb-ce2249be4a1b
  BUCKET_PORT: "30005"
  BUCKET_REGION: ""
  BUCKET_SUBREGION: ""
kind: ConfigMap
metadata:
  creationTimestamp: "2019-10-29T00:49:36Z"
  finalizers:
  - objectbucket.io/finalizer
  labels:
    app: noobaa
    bucket-provisioner: openshift-storage.noobaa.io-obc
    noobaa-domain: openshift-storage.noobaa.io
  name: test21obc
  namespace: openshift-storage
  ownerReferences:
  - apiVersion: objectbucket.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ObjectBucketClaim
    name: test21obc
    uid: fb1d5c62-f9e5-11e9-9159-0a0e10271dfb
  resourceVersion: "176511"
  selfLink: /api/v1/namespaces/openshift-storage/configmaps/test21obc
  uid: fb417036-f9e5-11e9-bbf3-0204af9750f1

**Comment by mulbc** [comment]
What I see is:
`System Phase is "Configuring". Waiting for phase ready ...`

Is it possible that you continued before Noobaa was installed completely?
--> Then we just need to put in text to tell the students to wait until X

If you waited and it didn't change, we might need to diagnose this further

**Comment by jeanchlopez** [comment]
Retried many time and nooba status was OK even in the dashboard.

Tried to reproduce this morning on RHPDS but could not.

**Comment by mulbc** [comment]
I'll close it then, keep it in the back of my head and will re-open the issue if we face it again
