### ISSUE TITLE
Noobaa Client vs macOS Version and HomeBrew

### ISSUE THREAD

**Issue by jeanchlopez** [red-hat-storage/ocs-training#66]
**Describe the bug**
noobaa client can not be installed via homebrew on macOS Sierra (10.12)

**Section in which you face the issue**
MCG testing

**To Reproduce**
1. brew install noobaa/noobaa/noobaa
2. Build error after go mod vendor

**Expected behavior**
Works fine on macOS 10.14

**Environment**
 - OS: macOS Sierra 10.12.6

**Did you use OCP deployed by the RHPDS workshop?**
No

**Additional context**

**Comment by jeanchlopez** [comment]
Foudn a workaround that should be documented

curl -s https://api.github.com/repos/noobaa/noobaa-operator/releases/latest | grep "mac" | cut -d : -f 2,3 | tr -d \" | wget -qi - ; mv noobaa-mac-* noobaa
chmod +x noobaa
sudo su
mv ./noobaa /usr/bin/
exit

noobaa
._   _            ______
| \ | |           | ___ \
|  \| | ___   ___ | |_/ / __ _  __ _
| . \ |/ _ \ / _ \| ___ \/ _\ |/ _\ |
| |\  | (_) | (_) | |_/ / (_| | (_| |
\_| \_/\___/ \___/\____/ \__,_|\__,_|

Install:
  install      Install the operator and create the noobaa system
  uninstall    Uninstall the operator and delete the system
  status       Status of the operator and the system

Manage:
  backingstore Manage backing stores
  bucketclass  Manage bucket classes
  obc          Manage object bucket claims

Advanced:
  operator     Deployment using operator
  system       Manage noobaa systems
  bucket       Manage noobaa buckets
  pvstore      Manage noobaa pv store
  crd          Deployment of CRDs
  olm          OLM related commands

Other Commands:
  options      Print the list of global flags
  version      Show version

Use "noobaa <command> --help" for more information about a given command.

noobaa version
INFO[0000] CLI version: 2.0.4
INFO[0000] noobaa-image: noobaa/noobaa-core:5
INFO[0000] operator-image: noobaa/noobaa-operator:2.0.4

Note that there is a typo in the manual instruction for macOS
Guide says
curl -s https://api.github.com/repos/noobaa/noobaa-operator/releases/latest | grep "mac" | cut -d : -f 2,3 | tr -d \" | wget -qi - ; mv noobaa-linux-* noobaa

Should read 
curl -s https://api.github.com/repos/noobaa/noobaa-operator/releases/latest | grep "mac" | cut -d : -f 2,3 | tr -d \" | wget -qi - ; mv noobaa-mac-* noobaa

**Comment by mulbc** [comment]
Resolved by merging https://github.com/red-hat-storage/ocs-training/pull/64
