### ISSUE TITLE
Replace RWX application example with File Uploader

### ISSUE THREAD

**Issue by netzzer** [red-hat-storage/ocs-training#70]
**Do you need more detailed steps on an existing section? Please describe.**
The current RWX CephFS example requires that podman be installed to verify use of the deployed registry.

**Describe what you would like to see**
Replace this RWX example in ocs4.adoc with File Uploader application example

**Comment by mulbc** [comment]
Solved by https://github.com/red-hat-storage/ocs-training/pull/75
