### ISSUE TITLE
Add pre-req for watch command on macOS clients

### ISSUE THREAD

**Issue by jeanchlopez** [red-hat-storage/ocs-training#74]
**Do you need more detailed steps on an existing section? Please describe.**
Latest set of instructions has switched to using the -w option on the OC commands. However this flag do not provide the same tracking experience.

e.g. oc get csv -n openshift-storage -w
Will prvide an update when a csv changes status but will not display the actual status it transitioned to.

**Describe what you would like to see**
In Appendix A, in the macOS steps, add the following

Install the watch command on your Mac using Homebrew
`brew install watch`

Alternative, add the following lines to your $HOME/.profile
`function watch {`
`   while :; do clear; date; echo; $@; sleep 2; done`
`}`

Then reload your profile with source $HOME/.profile

**Describe alternatives you've considered**
Would allow us to switch back to the more detailed output of the watch 'oc command' output.

**Additional context**
N/A

**Comment by mulbc** [comment]
We decided to revert to watch and tell (Mac) people to install watch
