### ISSUE TITLE
OCP4OCS lab should be region independent

### ISSUE THREAD

**Issue by steven-ellis** [red-hat-storage/ocs-training#76]
**Describe what you would like to see**
Current deployment guide assumes that the lab is deployed in the AWS region us-east-1.

As the lab can support generic AWS deploy OCP 4.2 instance we should try to support deployment into any region including Europe and APAC. The latency to us-east-1 is very high when using the lab in part of APAC including Korea which have local AWS regions.

**Describe alternatives you've considered**
Always using us-east-1

**Comment by mulbc** [comment]
Can you explain which part is not region independent?
Currently the only thing that comes to my mind are the worker-ocs yaml files - anywhere else?

**Comment by steven-ellis** [comment]
The instructions and the worker-ocs yaml files are currently region specific.

I'm working on a patch to resolve this under
https://github.com/steven-ellis/ocs-training/blob/region-neutral/ocp4ocs4/ocs4.adoc

Fixing the region is easy, making sure we pickup the region specific AMI is a bit harder.

**Comment by steven-ellis** [comment]
Sorry hit the wrong button - didn't mean to close this issue.

Two parts to the problem

- need to replace the region identified in the yaml for the ocs workers
- need to update the AMI reference in the yaml

**Comment by mulbc** [comment]
Discussed this with Annette... we do not support this, but will accept a PR that would add the machinesets to the repo in the master branch if you're willing to provide these.
