### ISSUE TITLE
Section 3.1 ocp4ocs4/ocs4.adoc error

### ISSUE THREAD

**Issue by therevoman** [red-hat-storage/ocs-training#86]
**Describe the bug**

In Section 3.1 a command is provided to map the pv's to the Ceph RDB's, followed by a command that uses the PVC name from the output.   However, the command does not show PVC information

oc get pv -o 'custom-columns=NAME:.spec.claimRef.name,STORAGECLASS:.spec.storageClassName,RBD:.spec.csi.volumeHandle'

**Section in which you face the issue**
Provide the Section title or a link to the section
3.1

**To Reproduce**
# oc get pv -o 'custom-columns=NAME:.spec.claimRef.name,STORAGECLASS:.spec.storageClassName,RBD:.spec.csi.volumeHandle'
# output:  
`$ oc get pv -o 'custom-columns=NAME:.spec.claimRef.name,STORAGECLASS:.spec.storageClassName,RBD:.spec.csi.volumeHandle'
NAME                      STORAGECLASS                  RBD
rook-ceph-mon-a           gp2                           <none>
rook-ceph-mon-b           gp2                           <none>
rook-ceph-mon-c           gp2                           <none>
ocs-deviceset-0-0-4hsvl   gp2                           <none>
ocs-deviceset-1-0-wcf2s   gp2                           <none>
ocs-deviceset-2-0-mnqf9   gp2                           <none>
db-noobaa-core-0          ocs-storagecluster-ceph-rbd   0001-0011-openshift-storage-0000000000000001-d6501a64-ff2b-11e9-a5dd-0a580a800405
postgresql                ocs-storagecluster-ceph-rbd   0001-0011-openshift-storage-0000000000000001-c9b201e7-ff2d-11e9-a5dd-0a580a800405
`

**Expected behavior**
The graphic shows PVC as a listed column

**Screenshots**

**Environment**
 - OS: [e.g. OSX, Fedora,...]

**Did you use OCP deployed by the RHPDS workshop?**
No.  manually created 4.2.2 cluster, then followed the training doc.

**Additional context**

**Comment by mulbc** [comment]
Thanks for reporting this - you are absolutely right and I'll fix the command...
