### ISSUE TITLE
obc command is missing the namespace 

### ISSUE THREAD

**Issue by tamireran** [red-hat-storage/ocs-training#90]
**Describe the bug**
`oc get obc test21obc -o yaml `

Should be replaced with 
`oc get obc test21obc -o yaml  -n openshift-storage`

**Section in which you face the issue**
6.2 
https://github.com/red-hat-storage/ocs-training/tree/master/ocp4ocs4#62-creating-an-object-bucket-claim

**Did you use OCP deployed by the RHPDS workshop?**
Yes

**Additional context**

**Comment by mulbc** [comment]
Fixed by fa3f4951ddae63e971ac9510f674fe056747c2f8
