### ISSUE TITLE
node labels 'openshift-storage' not applied, has to be done by hand

### ISSUE THREAD

**Issue by joshmsmith** [red-hat-storage/ocs-training#99]
**Describe the bug**
In '2.2. Installing the OCS operator', on the OCS configuration screen, when I hit 'Create OCS Cluster Service' - I get an error, and the pods can't be scheduled because they can't find nodes matching 'openshift-storage'.

Hand-applying the node labels seems to work.

**Section in which you face the issue**
2.2. Installing the OCS operator

**Expected behavior**
Pods would schedule on the storage nodes.

**Environment**
Chrome

**Did you use OCP deployed by the RHPDS workshop?**
Yes 

**Additional context**
Tried it a couple of times, tried uninstalling/reinstalling the operator.

**Comment by mulbc** [comment]
Could you describe a bit more what kind of error you are seeing when you click on the `Create OCS Cluster Service` button?

**Comment by netzzer** [comment]
Did you make sure to select 3x worker nodes in different AWS zones. They would be the 3 that result from this oc command:
```
oc get nodes --show-labels | grep storage-node |cut -d' ' -f1
```

**Comment by mulbc** [comment]
Closing since this is stale

**Comment by joshmsmith** [comment]
I did select nodes in three different clusters.
I got an error that the cluster couldn't install, and when I got the pods they were listed as unschedulable.
Sorry, it's been a busy week or so.
